Update to the name function urllib.urlopen
scalability4all/voice-enabled-chatbot pull request #22
Opened 2020-03-03 01:07 UTC by tacigomess

According to the https://docs.python.org/3/library/urllib.request.html#module-urllib.request the name of the function has been changed
to urllib.request.urlopen

2020-03-04 14:03 UTC, satyammittal requested changes

2020-03-04 14:03 UTC, satyammittal commented on google_places.py
> +    response = urllib.request.urlopen(url)
You have to directly import module `urllib.request` to make it work.

2020-03-05 11:42 UTC, arxcruz commented
Instead of use urllib, just use requests as in the other pieces here.

2020-03-14 10:41 UTC, satyammittal requested changes
Please update branch with latest changes.

2020-03-14 12:38 UTC, closed without merging